<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Admin;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdmins(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from(Admin::class, 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%ROLE_SUPER_ADMIN%');

        return $qb->getQuery()->getResult();
    }

    public function getId($username){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from(Admin::class, 'u')
            ->where('u.username LIKE :username')
            ->setParameter('username', $username);

        return $qb->getQuery()->getResult();
    }
}
