<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Compagnie;

/**
 * CourtierCompagnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtierCompagnieRepository extends \Doctrine\ORM\EntityRepository
{
}
