compagnie_index:
    path:     /
    defaults: { _controller: "AppBundle:Compagnie:index" }
    methods:  GET

compagnie_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Compagnie:show" }
    methods:  GET

compagnie_new:
    path:     /new
    defaults: { _controller: "AppBundle:Compagnie:new" }
    methods:  [GET, POST]

compagnie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Compagnie:edit" }
    methods:  [GET, POST]

compagnie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Compagnie:delete" }
    methods:  DELETE

