police_index:
    path:     /
    defaults: { _controller: "AppBundle:Police:index" }
    methods:  GET

police_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Police:show" }
    methods:  GET

police_new:
    path:     /new
    defaults: { _controller: "AppBundle:Police:new" }
    methods:  [GET, POST]

police_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Police:edit" }
    methods:  [GET, POST]

police_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Police:delete" }
    methods:  DELETE