primerc_index:
    path:     /
    defaults: { _controller: "AppBundle:PrimeRC:index" }
    methods:  GET

primerc_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:PrimeRC:show" }
    methods:  GET

primerc_new:
    path:     /new
    defaults: { _controller: "AppBundle:PrimeRC:new" }
    methods:  [GET, POST]

primerc_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:PrimeRC:edit" }
    methods:  [GET, POST]

primerc_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:PrimeRC:delete" }
    methods:  DELETE
